### ISSUE TITLE
Add yveCRV (Backscratcher) and yvstETH (Lido Staked Ether Vault) to Vaults UI

### ISSUE THREAD

**Issue by dudesahn** [yearn/yearn-finance#101]
**Is your feature request related to a problem? Please describe.**
Yearn has two great products that are not featured in v2: our Backscratcher and our Lido staked ether vault. 

**Describe the solution you'd like**
Implement the yveCRV Backscratcher and the yvstETH Vault at the top of the Vaults page to bring them more attention.

**Describe alternatives you've considered**
While the original plan is to put these on their own separate page, that will lead to these products being hidden and forgotten about. They should be at the very front of a user's attention, especially since the more CRV Yearn holds, the better our yields will be.

**Additional context**
yveCRV contract: 0x7CE6fDBCc4C22385D1BE50898f00fc8D0500A807
yvstETH contract: 0x15a2B3CfaFd696e1C783FE99eed168b78a3A371e

We would also want to include yield (growth) for both of these. For yveCRV it would be the 3Crv returns, for yvstETH it would be the staking returns.

**Comment by hantuzun** [comment]
Backscratcher is added at the moment, looking forward to Lido.

**Comment by dudesahn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add yvstETH to Vaults UI](https://trello.com/c/onHvUs57/100-add-yvsteth-to-vaults-ui)

**Comment by dudesahn** [comment]
Out of scope for v2, yvstETH can be included in v3 Labs page potentially
