### ISSUE TITLE
Column table sorting of vault list on v2

### ISSUE THREAD

**Issue by dudesahn** [yearn/yearn-finance#115]

**Comment by slaking** [comment]
Not sure if this is what this issue is for, but there's at least 2 sorting issues on the new UI:
- Sorting by total assets doesn't work
- Sorting by Growth doesn't seem to be correct (crvUSDN is on top, when there are other vaults with higher growth %)

**Comment by dudesahn** [comment]
Thanks @slaking, we actually just fixed sorting by total assets bug. 

The issue with sorting by growth is that we are actually displaying Net APY for the USDN vault vs Gross APY for all other vaults—this is done because USDN is abnormal in that it uses 50% as a `keepCRV` percentage, and we don't want to mislead users. We're talking about the best ways to get around this, but thank you for being vigilant!
