### ISSUE TITLE
Change the messaging for the backscratcher vault

### ISSUE THREAD

**Issue by defioccam** [yearn/yearn-finance#163]
## Description

The messaging for the backscratcher vault  on yearn.finance/vaults does not currently inform users that they can obtain yvecrv more cheaply from sushiswap. Instead, it instructs users to lock up CRV and then "After depositing join WETH/yveCRV-DAO pool for 🍣". This messaging is damaging in two ways
1. It does new purchasers of yvecrv a disservice by guiding them to obtain yvecrv at an above-market price
2. It removes the price support of yvecrv by shunting buy pressure for it away from the sushiswap yvecrv-eth pair and towards the overpriced backscratcher vault. 

As a consequence, the price of yvecrv is now 60% the price of CRV and the yvecrv-eth pool has essentially become exit liquidity for yvecrv holders.     

![image](https://user-images.githubusercontent.com/78896318/107610275-139b3e00-6bf6-11eb-83a2-1dda4a29804b.png)
 
**Expected behavior**
The copy on the backscratcher vault should inform users that they may be able to obtain yvecrv more cheaply on Sushiswap. Additionally, it should educate users that Pickle jars will provide price support for yvecrv by buying it from the the yvecrv-eth sushiswap pair    

This needs to be fixed quickly. The bigger the divergence between the price of CRV and the price of yvecrv, the harder it will be to bring the two back to parity and the worse the UX for yvecrv holders who took a chance on a promising yearn product.

**Comment by ibhi** [comment]
+1

**Comment by dudesahn** [comment]
This is currently being addressed and should be resolved shortly

**Comment by dudesahn** [comment]
This was closed by #384
