### ISSUE TITLE
Fix CREAM withdrawal calculation and add warning

### ISSUE THREAD

**Issue by dudesahn** [yearn/yearn-finance#168]
# Bounty
## Tasks
- Fix cream withdrawal calculation
- Add a warning if a user tries to withdraw more liquidity than is available

Bounty: $600
Site: v1.yearn.finance

### Context
- Some transactions are failing (if a user tries to withdraw and there is not enough liquidity)
- See: https://etherscan.io/tx/0xae9eb85d5dd5bfdc6f744760a8da984c87291c9e33411346b262014eb6b9e8ad#eventlog
- See: https://compound.finance/docs/comptroller#error-codes
- Fix: Disable withdraw button if user tries to withdraw more than the market holds
- Fix: Put a tooltip on the withdraw button that tells the user they must wait until the market has more liquidity
- It's not possible to withdraw max on v1 cream because our withdrawal calculations are wrong
- Reach out to Jeremy if you get stuck
- Fix: Follow instructions in the screenshot below

![IMAGE 2021-02-16 00:10:31](https://user-images.githubusercontent.com/23222916/108020893-622c4c00-6feb-11eb-96b4-927b2e4481e2.jpg)

**Comment by dudesahn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix CREAM withdrawal calculation and add warning](https://trello.com/c/VNUmklln/29-fix-cream-withdrawal-calculation-and-add-warning)

**Comment by 0xModene** [comment]
Is this bounty still open?

**Comment by dudesahn** [comment]
Out of scope for v2 now
