### ISSUE TITLE
on yearn.finance， The wallet data of the ropsten test network will be displayed

### ISSUE THREAD

**Issue by Zhang-Jony** [yearn/yearn-finance#280]
on https://yearn.finance/vaults ,if my wallet connect ropsten network,"Available to deposit" will show the count of my wallet.And i can deposit it,but the balance always 0.0000
![image](https://user-images.githubusercontent.com/4023459/116806281-85808500-ab5e-11eb-8497-cc0c19f19116.png)

**Comment by dudesahn** [comment]
Website has been updated to warn user when they load the page using a different wallet other than mainnet ETH
