### ISSUE TITLE
APY column on mobile view

### ISSUE THREAD

**Issue by RABSON-DAO** [yearn/yearn-finance#293]
Thank you very much for such a wonderful DeFi product.

I have a request if possible:

When accessing [the Yearn Vaults](https://yearn.finance/vaults) interface on mobile, the `Growth / APY` column is not visible which makes it hard to choose which pools to deposit funds to and start farming/ earning yield.

Could you make the `Growth/APY` column visible on mobile?

Thank you in advance.

**Comment by dudesahn** [comment]
For now, if you need to view APY on mobile, we recommend using https://yearn.fi. 

APY on mobile will be added in our v3, which will be coming soon.
