### ISSUE TITLE
yveBoost-ETH Vault: 500 response of zapper

### ISSUE THREAD

**Issue by aleacevedo** [yearn/yearn-finance#402]
Before opening a new issue, please take a moment to review our [**community guidelines**](https://github.com/iearn-finance/yearn-finance/blob/develop/CONTRIBUTING.md) to make the contribution process easy and effective for everyone involved.

## Description

When you try to zap-in into yveBoost-ETH Vault it make a request to 
```
https://api.zapper.fi/v1/zap-in/pickle/transaction?api_key=f589c526-31ae-4f74-b055-9441c9eeed5a&slippagePercentage=0.01&gasPrice=20000000000&poolAddress=0xced67a187b923f0e5ebcc77c7f2f7da20099e378&sellTokenAddress=0x0000000000000000000000000000000000000000&sellAmount=300000000000000000&ownerAddress=0x81cdeab9c9727cf54df26d849bc21e5395279233
```
and that request returns 

```
error: "Internal Server Error"
message: "Price not supported for token 0x9d409a0a012cfba9b15f6d4b36ac57a46966ab9a"
statusCode: 500
```

## Steps to reproduce

Try to zap-in into yveBoost-ETH Vault with any coin

**Expected behavior**
Go into yveBoost-ETH Vault

## Versions

- Browser: Brave
- yearn-finance: v2
- Node/NPM:

**Comment by dudesahn** [comment]
@aleacevedo thanks for pointing this out, we reached out to zapper and they fixed the issue on their end. I tested this evening and confirmed it is fixed; closing this issue now
