### ISSUE TITLE
[Gnosis Safe] Unable to fetch app icon on mainnet

### ISSUE THREAD

**Issue by JagoFigueroa** [yearn/yearn-finance#454]
## Description
Hey guys, basically a copy of what I reported in our own board (https://github.com/gnosis/safe-apps-list/issues/101). We are failing to fetch the icon for your app on mainnet and we would love to display it to users :) 

## Steps to reproduce
Go to the apps section.

## Obtained result
![Screenshot 2021-12-22 at 12 35 03](https://user-images.githubusercontent.com/92332710/147087239-f92cb345-6dd3-4c12-86c4-34445e04e277.png)

**Comment by mmv08** [comment]
This was fixed. Actually, it was the wrong URL on the config service. Could you please close the issue in yearn repo?

**Comment by JagoFigueroa** [comment]
Good to know! Only because it's you ;)
