### ISSUE TITLE
Keep v2 CTA buttons deposit/withdraw in sync with previous v1 flow

### ISSUE THREAD

**Issue by storming0x** [yearn/yearn-finance#49]
**Is your feature request related to a problem? Please describe.**
v2 has the CTA (Call to action) for depositing and withdrawing in a different position and labels from v1 which from early reports may confuse users. Approve is a call to action when it could be Deposit <Deposit> and like v1 starts two transactions.

v2 CTA buttons configurations
<img width="1231" alt="Screen Shot 2021-01-19 at 12 01 54" src="https://user-images.githubusercontent.com/6074987/105074810-7d3c8800-5a4e-11eb-8b55-1e33743787cd.png">

Compared to v1 CTA buttons

![Screen Shot 2021-01-19 at 12 00 47](https://user-images.githubusercontent.com/6074987/105074848-8a597700-5a4e-11eb-8b89-1c06c9918850.png)

**Describe the solution you'd like**
This may be complemented with the opinion of a UX expert more than my opinion, but keeping the same configuration and UI flow as v1 is a good middle ground to solve possible issues when interacting with UI.

**Describe alternatives you've considered**
Could be complemented with a bigger UX study of how easy is to deposit and withdraw for users in new UI.

**Additional context**

**Comment by WrongNebula** [comment]
Had a discussion on this subject with @x48-crypto and we decided to keep it different, main argument is that on vaults list the "Available to deposit" amount is located on the right side, thus we put the deposit field on the right side as well, so it fits under the "Available to deposit" when you expand the vault UI.

**Comment by dudesahn** [comment]
Not relevant for v2 anymore
