### ISSUE TITLE
Formatting is incorrect in graph section of website

### ISSUE THREAD

**Issue by Grandthrax** [yearn/yearn-finance#72]
![image](https://user-images.githubusercontent.com/1507729/105455028-c8d37980-5c7a-11eb-800a-0bc69a7a7586.png)

1. Numbers should be formatted. Most are scaled by decimals. Performance fee and management fee is a percent out of 1,000.
2. X-axis is in block number when should be date/time.
3. Sizing doesn't fit correctly on my screen.
4. Timeframe default should be 1 week not 1 month.

**Comment by dudesahn** [comment]
Not currently featured on website anymore
